version: '3.7'

services:

  static.api:
    container_name: "static-api"
    image: elwark/static.api:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 3000
    ports:
      - "3000:3000"