version: '3.7'

services:

  storage.api:
    container_name: "storage-api"
    image: elwark/storage.api:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 3000
    ports:
      - "3000:3000"