version: '3.7'

services:

  api:
    container_name: "elwark_storage_api"
    image: elwark/storage.api:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 80
    ports:
      - "3000:80"