name: Deploy to docker hub

on:
   push:
     branches:    
      - master
     tags:
       - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      
      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo $(date '+%Y%m%d%H%M%S'))
      
      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: nmakhmutov/elwark.storage/api
          registry: docker.pkg.github.com
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}
          dockerfile: Dockerfile
          tags: "latest,${{ env.RELEASE_VERSION }}"
