name: CI

on:
  push:
    branches: [ master ] 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%s')"
      
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.GH_TOKEN }} | docker login docker.pkg.github.com -u nmakhmutov --password-stdin

      - name: Build the Docker image
        run: docker build . --file ./Dockerfile --tag docker.pkg.github.com/nmakhmutov/elwark.storage/storage.api:${{steps.date.outputs.date}}
    
      - name: Publish the Docker image
        run: docker push docker.pkg.github.com/nmakhmutov/elwark.storage/storage.api:${{steps.date.outputs.date}}
