name: Deploy to docker hub

on:
   push:
     branches:    
      - master
     tags:
       - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master

      - name: Login to docker hub
        if: success()
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.GH_TOKEN }}
          DOCKER_REGISTRY_URL: docker.pkg.github.com

      - name: Build :latest
        if: success()
        run: docker build -t docker.pkg.github.com/${{ github.repository }}/api:latest .
      
      - name: Push to docker hub :latest
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push docker.pkg.github.com/${{ github.repository }}:latest