name: Deploy to docker hub

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      
      - name: Get release version
        id: get_version
        run: echo ::set-env name=VERSION::$(echo $(date '+%Y%m%d%H%M%S'))
      
      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: nmakhmutov/elwark.storage/api
          registry: docker.pkg.github.com
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}
          dockerfile: Dockerfile
          tags: "${{ env.VERSION }},latest"
